Update the bootstrap script
The bootstrap script now uses the same logic for determining and
downloading the latest prebuilt version as the autoupdate
mechanism.

Change-Id: I0cc17c3fc47f6dd9bbeaa4dbe10a708f5baaaee9

diff --git a/scripts/bootstrap_jiri b/scripts/bootstrap_jiri
--- a/scripts/bootstrap_jiri
+++ b/scripts/bootstrap_jiri
@@ -88,24 +88,10 @@ fi
 
 # Determine and validate the version of jiri.
 readonly TARGET="${HOST_OS}-amd64"
-readonly VERSION_URL="${VERSION_BASE_URL}/${TARGET}?format=TEXT"
-readonly ENCODED_VERSION="$(curl -sSf "${VERSION_URL}")"
-readonly BASE64_REGEX="^[0-9a-zA-Z+/=]+"
-if [[ ! "${ENCODED_VERSION}" =~ ${BASE64_REGEX} ]]; then
-  # This might happen if there's a server error, or maybe ${TARGET}/version.sha doesn't exist.
-  echo "Encoded jiri version does not look like base64" 1>&2
-  echo "URL: ${VERSION_URL}" 1>&2
-  echo "" 1>&2
-  echo "Maybe ${TARGET} isn't supported?" 1>&2
-  exit 1
-fi
-
-readonly VERSION="$(echo "${ENCODED_VERSION}" | ${BASE64_CMD} | tr -d '[[:space:]]')"
-readonly SHA1_REGEX="[0-9a-f]{40}"
-if [[ ! "${VERSION}" =~ ${SHA1_REGEX} ]]; then
-  # This might happen if ${TARGET}/version.sha contains something other than a git SHA-1 hash.
-  echo "Decoded jiri version does not look like a git SHA-1 hash:" 1>&2
-  echo "${VERSION}" 1>&2
+readonly COMMIT_URL="${JIRI_REPO_URL}/+refs/heads/master?format=JSON"
+readonly VERSION=$(curl -sSf "${COMMIT_URL}" | sed -n 's/.*"value": "\([0-9a-f]\{40\}\)"/\1/p')
+if [[ -z ${VERSION} ]]; then
+  echo "Cannot determine the latest jiri version" 1>&2
   exit 1
 fi
 
